package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseAd;

/**
 * Generated by Jboot.
 */
@Table(tableName = "ad", primaryKey = "id")
public class Ad extends BaseAd<Ad> {
	
}
