package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseCode;

/**
 * Generated by Jboot.
 */
@Table(tableName = "code", primaryKey = "code_id")
public class Code extends BaseCode<Code> {
	
}
