package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BasePtOrder;

/**
 * Generated by Jboot.
 */
@Table(tableName = "pt_order", primaryKey = "order_id")
public class PtOrder extends BasePtOrder<PtOrder> {
	
}
