package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseReadRecord;

/**
 * Generated by Jboot.
 */
@Table(tableName = "read_record", primaryKey = "read_record_id")
public class ReadRecord extends BaseReadRecord<ReadRecord> {
	
}
