package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseShop;

/**
 * Generated by Jboot.
 */
@Table(tableName = "shop", primaryKey = "shop_id")
public class Shop extends BaseShop<Shop> {
	
}
