package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseSysData;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_data", primaryKey = "id")
public class SysData extends BaseSysData<SysData> {
	
}
