package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseSysLog;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_log", primaryKey = "id")
public class SysLog extends BaseSysLog<SysLog> {
	
}
