package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseSysRole;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_role", primaryKey = "id")
public class SysRole extends BaseSysRole<SysRole> {
	
}
