package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseSysUser;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_user", primaryKey = "id")
public class SysUser extends BaseSysUser<SysUser> {
	
}
