package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseSysUserRole;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_user_role", primaryKey = "id")
public class SysUserRole extends BaseSysUserRole<SysUserRole> {
	
}
