package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseUserComment;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user_comment", primaryKey = "user_comment_id")
public class UserComment extends BaseUserComment<UserComment> {
	
}
