package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseUserLogin;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user_login", primaryKey = "user_login_id")
public class UserLogin extends BaseUserLogin<UserLogin> {
	
}
