package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseUserCheck;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user_check", primaryKey = "user_check_id")
public class UserCheck extends BaseUserCheck<UserCheck> {
	
}
