package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserLogin<M extends BaseUserLogin<M>> extends JbootModel<M> implements IBean {

	public void setUserLoginId(java.lang.String userLoginId) {
		set("user_login_id", userLoginId);
	}
	
	public java.lang.String getUserLoginId() {
		return getStr("user_login_id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public void setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
	}
	
	public java.util.Date getLastLoginTime() {
		return get("last_login_time");
	}

	public void setLastLogoutTime(java.util.Date lastLogoutTime) {
		set("last_logout_time", lastLogoutTime);
	}
	
	public java.util.Date getLastLogoutTime() {
		return get("last_logout_time");
	}

	public void setRelationId(java.lang.String relationId) {
		set("relation_id", relationId);
	}
	
	public java.lang.String getRelationId() {
		return getStr("relation_id");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

}
