package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserCheck<M extends BaseUserCheck<M>> extends JbootModel<M> implements IBean {

	public void setUserCheckId(java.lang.Long userCheckId) {
		set("user_check_id", userCheckId);
	}
	
	public java.lang.Long getUserCheckId() {
		return getLong("user_check_id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public void setUserCommentId(java.lang.String userCommentId) {
		set("user_comment_id", userCommentId);
	}
	
	public java.lang.String getUserCommentId() {
		return getStr("user_comment_id");
	}

	public void setReporterId(java.lang.String reporterId) {
		set("reporter_id", reporterId);
	}
	
	public java.lang.String getReporterId() {
		return getStr("reporter_id");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public void setUpdated(java.util.Date updated) {
		set("updated", updated);
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

}
