package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReadRecord<M extends BaseReadRecord<M>> extends JbootModel<M> implements IBean {

	public void setReadRecordId(java.lang.Integer readRecordId) {
		set("read_record_id", readRecordId);
	}
	
	public java.lang.Integer getReadRecordId() {
		return getInt("read_record_id");
	}

	public void setUserCommentId(java.lang.String userCommentId) {
		set("user_comment_id", userCommentId);
	}
	
	public java.lang.String getUserCommentId() {
		return getStr("user_comment_id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public void setUpdated(java.util.Date updated) {
		set("updated", updated);
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
